---
sudo: required
matrix:
  include:

    - env: TARGET="x86_64-unknown-linux"
      os: linux
      language: python

    - env: TARGET="x86_64-apple-darwin"
      os: osx
      language: c

cache:
  directories:
    - /usr/local

install:
  - ./install-ats.sh

script:
  - |
    if [ $TARGET = "x86_64-unknown-linux" ]
    then
      pip install yamllint
      yamllint .travis.yml
      yamllint .yamllint
      curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s .atsfmt.toml
    else
      echo "skipping..."
    fi
  - make

deploy:
  api_key:
    secure: "{{ travis_key }}"
  file: {{ project }}-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true
