license = "BSD3"
with_readme = true

[files]
templates = [ "Makefile"
            , "{{ project }}.dats"
            , ".gitignore"
            , ".travis.yml"
            , ".yamllint"
            , ".atsfmt.toml"
            ]
scripts = [ "install.sh" ]

[config]
version = "0.1.0"
version_control = "git"
